Vagrant.configure("2") do |config|
    config.vm.box = "ilker/ubuntu2004"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # Adjust memory as needed
        vb.cpus = 2          # Adjust CPU count as needed
    end

    config.vm.provision "ansible" do |ansible|
        ansible.become = true
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"  # Specify the path to your playbook
    end
end

